config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

resources :articles

get 'pages/about', to: 'pages#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
    
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
    def index
        @articles = Article.all
    end
    
    def new
       
       @article = Article.new
       
    end
    
    def edit
    end
    
    def update
       if @article.update(article_params)
           flash[:notice] = "article was successfully updated"
            # do something
            redirect_to article_path(@article) 
        else 
            render 'edit'
        end
    end
    
    def create
    
    @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "article was successfully created"
            # do something
            redirect_to article_path(@article) 
        else render 'new'
        end
    end

    def show
    end

    def destroy
        @article.destroy
        
        flash[:notice] = "article was successfully deleted"
        
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id]) 
        end
    
        def article_params
            params.require(:article).permit(:title, :description)
            
    end
    
end

app/controllers/concerns/pages_controller.rb
class PagesController <ApplicationController
    def home
        
    end
    
    def about
        
    end
    
end

app/controllers/welcome_controller.rb
# class WelcomeController <ApplicationController
#     def home
        
#     end
    
#     def about
        
#     end
    
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<h1>create an article</h1>

<% if @article.errors.any? %>
<h2>the following errors prevented the article from getting created</h2>


<ul>
    <% @article.errors.full_messages.each do |msg| %>

    <li><%= msg %> </li>
    <% end %>

</ul>

<% end %>


<%= form_for @article do |f| %>

<p>
    
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
    
    
</p>

<p>
    <%= f.label :description %> <br/>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %> 
</p>


<% end %>

<%= link_to "back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>listing all articles</h1>


<p>
    <%= link_to "Create New Article", new_article_path %>
</p>




<table>
    <tr>
        <th> Title </th>
        <th> Description </th>
    </tr>
    
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "are you sure?"} %></td>
    </tr>
   
    <% end %>
</table>

<%= link_to "back to articles listing", articles_path %>

app/views/articles/new.html.erb
<h1>create an article</h1>


<%= render 'form' %>

app/views/articles/show.html.erb
<h1>showing new article</h1>


<p>
    Title: <%= @article.title %>
</p>

<p>
    Description: <%= @article.description %>
</p>


<%= link_to "edit this article", edit_article_path(@article) %> | 

<%= link_to "back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
     <ul>
       
       <li>
         <%= msg %>
       </li>
       
     </ul>
 
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
  <%= render 'layouts/messages' %> 
   
  <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>this is the about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>this is the homepage of my blog app</h1>

<%= link_to = "alpha blog", articles_path %> | <%= link_to "about", pages_about_path %>

<%= link_to image_tag('2.jpg'), 'https://github.com/zenidith' %>